name: PullRequest

on:
  pull_request:
    # this action will be triggered each time a PR was made against branch master.
    branches: [master]
    # this workflow will only be triggered when a PR is created. Following pushes do not trigger this workflow again.
    types: [opened]

jobs:
  build:
    # name of the job, you can rename this as needed
    name: Crafting Preview Link
    runs-on: [ubuntu-latest]
    env:
      # This tells the action to use the token so that it can post a comment to PR.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: sandbox-launch-action # name of this step, you can rename this as needed
        uses: crafting-dev/sandbox-launch-action@v0.5.3 # update the version as needed
        with:
          # required inputs for sandbox-launch-action to specify the target template.
          template: TEMPLATE_NAME
